# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160119_1310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Посты',
        ),
    ]
