# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160119_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Посты'},
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
