# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20160119_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_autor',
            new_name='post_author',
        ),
    ]
