# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20160119_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_post',
            field=models.ManyToManyField(to='post.Post'),
        ),
    ]
