# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20160120_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(to='post.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=15, unique=True, verbose_name='Тег'),
        ),
    ]
