# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 12:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20160212_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст поста'),
        ),
    ]
