# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 15:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20160218_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст поста'),
        ),
    ]
